### ISSUE TITLE
How to deal with missing values in a series?

### ISSUE THREAD

**Issue by AkbarMarvasti-NOAA** [SEFSC/SEFSC-ODM-Management-History#3]

**Comment by AkbarMarvasti-NOAA** [comment]
@mollystevens-noaa

**Comment by mollystevens-noaa** [comment]
Hi @AkbarMarvasti-NOAA !  I received an email when you tagged me in this issue.  I'm glad you're able to find and open an issue on an existing SEFSC repository!  This repository relates to the Management History Project. Since it is a publicly shared repository, anyone can contribute an issue related to the project. This feature for facilitating collaboration is exciting! We've marked this practice issue as closed for now.

**Comment by AkbarMarvasti-NOAA** [comment]
Thanks for the practice.
